//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2300.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;

namespace HP.Csn.Business.KM.Services.SearchService
{
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="cs-2.0Port", Namespace="http://www.hp.com/seeker/cs")]
	[System.Xml.Serialization.SoapIncludeAttribute(typeof(WSMetaDataQuery))]
	[System.Xml.Serialization.SoapIncludeAttribute(typeof(WSSearchResult))]
	public class SearchService : CoreService
	{
    
		/// <remarks/>
		public SearchService() 
		{
			//this.Url = "http://ccedl01.cce.cpqcorp.net:80/cs-2.0/service";
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/cs", ResponseNamespace="http://www.hp.com/seeker/cs")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSSearchResults page(WSUserInfo wSUserInfo, WSPageRequest wSPageRequest) 
		{
			object[] results = this.Invoke("page", new object[] {
																	wSUserInfo,
																	wSPageRequest});
			return ((WSSearchResults)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult Beginpage(WSUserInfo wSUserInfo, WSPageRequest wSPageRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("page", new object[] {
															 wSUserInfo,
															 wSPageRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSSearchResults Endpage(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSSearchResults)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/cs", ResponseNamespace="http://www.hp.com/seeker/cs")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSSearchResults search(WSUserInfo wSUserInfo, WSSearchRequest wSSearchRequest, WSMetaDataQuery[] wSMetaDataQuerys) 
		{
			object[] results = this.Invoke("search", new object[] {
																	  wSUserInfo,
																	  wSSearchRequest,
																	  wSMetaDataQuerys});
			return ((WSSearchResults)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult Beginsearch(WSUserInfo wSUserInfo, WSSearchRequest wSSearchRequest, WSMetaDataQuery[] wSMetaDataQuerys, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("search", new object[] {
															   wSUserInfo,
															   wSSearchRequest,
															   wSMetaDataQuerys}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSSearchResults Endsearch(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSSearchResults)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/cs", ResponseNamespace="http://www.hp.com/seeker/cs")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSSearchResults sort(WSUserInfo wSUserInfo, WSSortRequest wSSortRequest) 
		{
			object[] results = this.Invoke("sort", new object[] {
																	wSUserInfo,
																	wSSortRequest});
			return ((WSSearchResults)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult Beginsort(WSUserInfo wSUserInfo, WSSortRequest wSSortRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("sort", new object[] {
															 wSUserInfo,
															 wSSortRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSSearchResults Endsort(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSSearchResults)(results[0]));
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSUserInfo", "java:com.hp.seeker.request")]
	public class WSUserInfo 
	{
    
		/// <remarks/>
		public int[] disclosureLevels;
    
		/// <remarks/>
		public string[] entitlements;
    
		/// <remarks/>
		public string portalId;
    
		/// <remarks/>
		public string userId;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSSortRequest", "java:com.hp.seeker.cs.request")]
	public class WSSortRequest 
	{
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int resultsPerPage;
    
		/// <remarks/>
		public string searchId;
    
		/// <remarks/>
		public string sessionId;
    
		/// <remarks/>
		public int sortCriterion1;
    
		/// <remarks/>
		public int sortCriterion2;
    
		/// <remarks/>
		public int sortCriterion3;
    
		/// <remarks/>
		public int sortOrder1;
    
		/// <remarks/>
		public int sortOrder2;
    
		/// <remarks/>
		public int sortOrder3;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSMetaDataQuery", "java:com.hp.seeker.cs.request")]
	public class WSMetaDataQuery 
	{
    
		/// <remarks/>
		public string name;
    
		/// <remarks/>
		public int type;
    
		/// <remarks/>
		public string[] values;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSSearchRequest", "java:com.hp.seeker.cs.request")]
	public class WSSearchRequest 
	{
    
		/// <remarks/>
		public int[] docTypes;
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int maxResults;
    
		/// <remarks/>
		public string query;
    
		/// <remarks/>
		public int resultsPerPage;
    
		/// <remarks/>
		public int searchCriteria;
    
		/// <remarks/>
		public string searchId;
    
		/// <remarks/>
		public string[] searchLanguages;
    
		/// <remarks/>
		public string sessionId;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSSearchResult", "java:com.hp.seeker.cs.result.search")]
	public class WSSearchResult 
	{
    
		/// <remarks/>
		public System.DateTime contentUpdateDate;
    
		/// <remarks/>
		public System.DateTime creationDate;
    
		/// <remarks/>
		public string disclosureLevel;
    
		/// <remarks/>
		public string docId;
    
		/// <remarks/>
		public string docRetrievalKey;
    
		/// <remarks/>
		public long docSize;
    
		/// <remarks/>
		public string docType;
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public System.Double rank;
    
		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
		public System.Byte[] synopsis;
    
		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
		public System.Byte[] title;
    
		/// <remarks/>
		public string uri;
    
		/// <remarks/>
		public string versionState;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSSearchResults", "java:com.hp.seeker.cs.result.search")]
	public class WSSearchResults 
	{
    
		/// <remarks/>
		public int documentsQualified;
    
		/// <remarks/>
		public int documentsReturned;
    
		/// <remarks/>
		public int documentsSearched;
    
		/// <remarks/>
		public WSSearchResult[] results;
    
		/// <remarks/>
		public string searchId;
    
		/// <remarks/>
		public string sessionId;
    
		/// <remarks/>
		public string suggestedQuery;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSPageRequest", "java:com.hp.seeker.cs.request")]
	public class WSPageRequest 
	{
    
		/// <remarks/>
		public int page;
    
		/// <remarks/>
		public int resultsPerPage;
    
		/// <remarks/>
		public string searchId;
    
		/// <remarks/>
		public string sessionId;
	}
}