//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2300.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;
namespace HP.Csn.Business.KM.Services.TaxonomyService
{

	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="ct-2.0Port", Namespace="http://www.hp.com/seeker/ct")]
	[System.Xml.Serialization.SoapIncludeAttribute(typeof(WSPMNode))]
	[System.Xml.Serialization.SoapIncludeAttribute(typeof(WSCVNode))]
	public class TaxonomyService : CoreService 
	{
    
		/// <remarks/>
		public TaxonomyService() 
		{
			//this.Url = "http://ccedl01.cce.cpqcorp.net:80/ct-2.0/service";
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/ct", ResponseNamespace="http://www.hp.com/seeker/ct")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSCVNode[] retrieveCV(WSUserInfo wSUserInfo, WSCVRequest wSCVRequest) 
		{
			object[] results = this.Invoke("retrieveCV", new object[] {
																		  wSUserInfo,
																		  wSCVRequest});
			return ((WSCVNode[])(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginretrieveCV(WSUserInfo wSUserInfo, WSCVRequest wSCVRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("retrieveCV", new object[] {
																   wSUserInfo,
																   wSCVRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSCVNode[] EndretrieveCV(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSCVNode[])(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/ct", ResponseNamespace="http://www.hp.com/seeker/ct")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSCVNode[] retrieveCVSubtree(WSUserInfo wSUserInfo, WSCVSubtreeRequest wSCVSubtreeRequest) 
		{
			object[] results = this.Invoke("retrieveCVSubtree", new object[] {
																				 wSUserInfo,
																				 wSCVSubtreeRequest});
			return ((WSCVNode[])(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginretrieveCVSubtree(WSUserInfo wSUserInfo, WSCVSubtreeRequest wSCVSubtreeRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("retrieveCVSubtree", new object[] {
																		  wSUserInfo,
																		  wSCVSubtreeRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSCVNode[] EndretrieveCVSubtree(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSCVNode[])(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/ct", ResponseNamespace="http://www.hp.com/seeker/ct")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSPMNode[] pmSearch(WSUserInfo wSUserInfo, WSPMSearchRequest wSPMSearchRequest) 
		{
			object[] results = this.Invoke("pmSearch", new object[] {
																		wSUserInfo,
																		wSPMSearchRequest});
			return ((WSPMNode[])(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginpmSearch(WSUserInfo wSUserInfo, WSPMSearchRequest wSPMSearchRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("pmSearch", new object[] {
																 wSUserInfo,
																 wSPMSearchRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSPMNode[] EndpmSearch(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSPMNode[])(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.hp.com/seeker/ct", ResponseNamespace="http://www.hp.com/seeker/ct")]
		[return: System.Xml.Serialization.SoapElementAttribute("result")]
		public WSPMNode[] retrievePMSubtree(WSUserInfo wSUserInfo, WSPMRequest wSPMRequest) 
		{
			object[] results = this.Invoke("retrievePMSubtree", new object[] {
																				 wSUserInfo,
																				 wSPMRequest});
			return ((WSPMNode[])(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginretrievePMSubtree(WSUserInfo wSUserInfo, WSPMRequest wSPMRequest, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("retrievePMSubtree", new object[] {
																		  wSUserInfo,
																		  wSPMRequest}, callback, asyncState);
		}
    
		/// <remarks/>
		public WSPMNode[] EndretrievePMSubtree(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSPMNode[])(results[0]));
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSUserInfo", "java:com.hp.seeker.request")]
	public class WSUserInfo 
	{
    
		/// <remarks/>
		public int[] disclosureLevels;
    
		/// <remarks/>
		public string[] entitlements;
    
		/// <remarks/>
		public string portalId;
    
		/// <remarks/>
		public string userId;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSPMRequest", "java:com.hp.seeker.ct.request")]
	public class WSPMRequest 
	{
    
		/// <remarks/>
		public int levels;
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int oid;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSPMNode", "java:com.hp.seeker.ct.result.taxo")]
	public class WSPMNode 
	{
    
		/// <remarks/>
		public int[] children;
    
		/// <remarks/>
		public string displayName;
    
		/// <remarks/>
		public string highLevelAudience;
    
		/// <remarks/>
		public string kmLevelDisplayName;
    
		/// <remarks/>
		public string kmLevelMetaDataName;
    
		/// <remarks/>
		public int level;
    
		/// <remarks/>
		public int oid;
    
		/// <remarks/>
		public int[] parents;
    
		/// <remarks/>
		public string phpId;
    
		/// <remarks/>
		public string platformId;
    
		/// <remarks/>
		public string productNumber;
    
		/// <remarks/>
		public System.DateTime webReleaseDate;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSPMSearchRequest", "java:com.hp.seeker.ct.request")]
	public class WSPMSearchRequest 
	{
    
		/// <remarks/>
		public int level;
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int maxResults;
    
		/// <remarks/>
		public bool searchBelow;
    
		/// <remarks/>
		public string searchStr;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSCVSubtreeRequest", "java:com.hp.seeker.ct.request")]
	public class WSCVSubtreeRequest 
	{
    
		/// <remarks/>
		public int levels;
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int oid;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSCVNode", "java:com.hp.seeker.ct.result.taxo")]
	public class WSCVNode 
	{
    
		/// <remarks/>
		public int[] children;
    
		/// <remarks/>
		public string displayName;
    
		/// <remarks/>
		public string kmLevelDisplayName;
    
		/// <remarks/>
		public string kmLevelMetaDataName;
    
		/// <remarks/>
		public int level;
    
		/// <remarks/>
		public int oid;
    
		/// <remarks/>
		public int[] parents;
    
		/// <remarks/>
		public string taggingValue;
	}

	/// <remarks/>
	[System.Xml.Serialization.SoapTypeAttribute("WSCVRequest", "java:com.hp.seeker.ct.request")]
	public class WSCVRequest 
	{
    
		/// <remarks/>
		public string locale;
    
		/// <remarks/>
		public int taxoId;
	}
}